import {CardData, TestimonialsData} from "@/app/lib/definitions";

export const cardsData: CardData[] = [
    {
        clubName1: "Paris Saint-Germain",
        img: "/assets/user1.png",
        price: "35 €",
        name: "Christophe",
        badg1: "/assets/clubBadg.svg",
        badg2: "/assets/clubBadg2.svg",
        clubName2: "Arsenal",
        city: "Madrid",
        date: "30/11/2023",
        published: "Published on",
        shieldA: "/assets/shieldA.svg",
        shieldS: "/assets/shieldS.svg",
        publishedDate: "18/11/2022",
    },
    {
        clubName1: "Paris Saint-Germain",
        img: "/assets/user1.png",
        price: "35 €",
        name: "Christophe",
        badg1: "/assets/clubBadg.svg",
        badg2: "/assets/clubBadg2.svg",
        clubName2: "Arsenal",
        city: "Madrid",
        date: "30/11/2023",
        published: "Published on",
        shieldA: "/assets/shieldA.svg",
        shieldS: "/assets/shieldS.svg",
        publishedDate: "18/11/2022",
    },
    {
        clubName1: "Paris Saint-Germain",
        img: "/assets/user1.png",
        price: "35 €",
        name: "Christophe",
        badg1: "/assets/clubBadg.svg",
        badg2: "/assets/clubBadg2.svg",
        clubName2: "Arsenal",
        city: "Madrid",
        date: "30/11/2023",
        published: "Published on",
        shieldA: "/assets/shieldA.svg",
        shieldS: "/assets/shieldS.svg",
        publishedDate: "18/11/2022",
    },
    {
        clubName1: "Paris Saint-Germain",
        img: "/assets/user1.png",
        price: "35 €",
        name: "Christophe",
        badg1: "/assets/clubBadg.svg",
        badg2: "/assets/clubBadg2.svg",
        clubName2: "Arsenal",
        city: "Madrid",
        date: "30/11/2023",
        published: "Published on",
        shieldA: "/assets/shieldA.svg",
        shieldS: "/assets/shieldS.svg",
        publishedDate: "18/11/2022",
    },
    {
        clubName1: "Paris Saint-Germain",
        img: "/assets/user1.png",
        price: "35 €",
        name: "Christophe",
        badg1: "/assets/clubBadg.svg",
        badg2: "/assets/clubBadg2.svg",
        clubName2: "Arsenal",
        city: "Madrid",
        date: "30/11/2023",
        published: "Published on",
        shieldA: "/assets/shieldA.svg",
        shieldS: "/assets/shieldS.svg",
        publishedDate: "18/11/2022",
    },
    {
        clubName1: "Paris Saint-Germain",
        img: "/assets/user1.png",
        price: "35 €",
        name: "Christophe",
        badg1: "/assets/clubBadg.svg",
        badg2: "/assets/clubBadg2.svg",
        clubName2: "Arsenal",
        city: "Madrid",
        date: "30/11/2023",
        published: "Published on",
        shieldA: "/assets/shieldA.svg",
        shieldS: "/assets/shieldS.svg",
        publishedDate: "18/11/2022",
    },
    {
        clubName1: "Paris Saint-Germain",
        img: "/assets/user1.png",
        price: "35 €",
        name: "Christophe",
        badg1: "/assets/clubBadg.svg",
        badg2: "/assets/clubBadg2.svg",
        clubName2: "Arsenal",
        city: "Madrid",
        date: "30/11/2023",
        published: "Published on",
        shieldA: "/assets/shieldA.svg",
        shieldS: "/assets/shieldS.svg",
        publishedDate: "18/11/2022",
    },
];

export const testimonialsData: TestimonialsData[] = [
    {
        key: 1,
        img: "/assets/user1.png",
        name: "Jenny Wilson",
        position: "Scout",
        review:
            "Eget eu rhoncus scelerisque sed quis. Ut tincidunt erat purus neque. Placerat consectetur risus vulputate orci nibh nunc aliquam. Pellentesque elit viverra natoque hendrerit in amet. Orci natoque at neque neque consequat. ",
    },
    {
        key: 2,
        img: "/assets/user2.png",
        name: "Ronald Richards",
        position: "Gestionnaire d`OS",
        review:
            "Eget eu rhoncus scelerisque sed quis. Ut tincidunt erat purus neque. Placerat consectetur risus vulputate orci nibh nunc aliquam. Pellentesque elit viverra natoque hendrerit in amet. Orci natoque at neque neque  ",
    },
    {
        key: 3,
        img: "/assets/user3.png",
        name: "Jacob Jones",
        position: "Coach",
        review:
            "Consectetur ut malesuada justo ut ullamcorper adipiscing. Convallis nisi lacus tempor lacus lorem a. Ut habitasse augue praesent elit tristique purus. Nunc nisl in urna egestas eu nunc arcu aenean proin. Tortor euismod vitae pellentesque !",
    },
    {
        key: 4,
        img: "/assets/user3.png",
        name: "Jacob Jones",
        position: "Coach",
        review:
            "Consectetur ut malesuada justo ut ullamcorper adipiscing. Convallis nisi lacus tempor lacus lorem a. Ut habitasse augue praesent elit tristique purus. Nunc nisl in urna egestas eu nunc arcu aenean proin. Tortor euismod vitae pellentesque !",
    },
    {
        key: 5,
        img: "/assets/user3.png",
        name: "Jacob Jones",
        position: "Coach",
        review:
            "Consectetur ut malesuada justo ut ullamcorper adipiscing. Convallis nisi lacus tempor lacus lorem a. Ut habitasse augue praesent elit tristique purus. Nunc nisl in urna egestas eu nunc arcu aenean proin. Tortor euismod vitae pellentesque !",
    },
    {
        key: 6,
        img: "/assets/user3.png",
        name: "Jacob Jones",
        position: "Coach",
        review:
            "Consectetur ut malesuada justo ut ullamcorper adipiscing. Convallis nisi lacus tempor lacus lorem a. Ut habitasse augue praesent elit tristique purus. Nunc nisl in urna egestas eu nunc arcu aenean proin. Tortor euismod vitae pellentesque !",
    },
];
